---
title: "Comprehensive Canadian Immigrant Guide"
author: "Vignesh C Iyer"
date: "7/27/2020"
output:
  pdf_document: default
  html_document: default
---
***
# First Things to Do After Landing in Canada
***

### When you arrive in Canada You must have: 

* your valid passport and/or travel documents 

  * your passport must be a regular, private citizen passport 

  * you can’t immigrate to Canada with a diplomatic, government service or public affairs passport 

* your Confirmation of Permanent Residence (COPR) and your permanent resident visa 

* proof that you have the funds to support yourself and your family after you arrive in Canada 

### When you arrive in Canada, you’ll meet an officer from the Canada Border Services Agency (CBSA). The officer will: 

* make sure you’re entering Canada before or on the expiry date shown on your COPR 

* make sure that you are the same person who was approved to travel to Canada (they may use your biometrics to do this) 

* ask to see your passport and other travel documents 

* ask you a few questions to make sure you still meet the terms to immigrate to Canada 
  
  * the questions will be similar to the ones you answered when you applied 
  
To help speed up your entry to Canada, keep your passport and other documents with you at all times. **Don’t pack them in your luggage**. 

***
## Disclosure of funds 
***
If you arrive in Canada with **more than CAN$10,000**, you must tell this to the CBSA officer. If you don’t tell them, you could be fined, and your funds could be seized.

## What to expect when you land in Canada 

Knowing what to expect when you land will contribute to a smooth experience. 

One of the first people you will meet at your point of arrival in Canada will be a friendly Canada customs agent. You will deal with your goods and landing certificates here. 

You’ll also meet other officials from Immigration Services. They will ask you to show your passport and visa papers. 

Immigration authorities will give you application forms for a variety of documents that you will need such as your: 

* Permanent Resident (PR) Card 
* Social Insurance Number (SIN) card 
* Health care card 
* Driver’s license 

You will need these cards to find work and start the clock on getting your provincial healthcare coverage in place. 

It’s important that you start the process to obtain these documents as soon as you land. 

When you’ll receive your Permanent Resident (PR) Card Your PR card is proof of your Canadian permanent resident status. 

You will need this card whenever you re-enter Canada. An immigration officer will tell you when you can expect to receive your PR Card. 

You will receive your wallet-sized plastic PR Card in the mail. So, be sure that you receive it within the time frame indicated by the immigration officer.

Important First Steps to take: 

1. Apply for your SIN Card Apply for your Social Insurance Number (SIN) as soon as you arrive in Canada. Without this number, you cannot get a job or apply for any government assistance or credit. In fact, without it, you are virtually a person without an identity in Canada. 

2. Apply for your Health Care Card You will need to apply for a health care card to receive free medical coverage in the province or territory where you plan to live. Apply for your health care card as soon as you land. If you plan to live in British Columbia or Ontario, there is a three-month waiting period before you will be covered by the public health care system. So, it’s important to apply for your health care card as soon as you land in either of these provinces. For all other provinces and territories, you health care coverage begins as soon as you arrive. 
[Ontario Health Insurance Plan](www.health.gov.on.ca/en/public/programs/ohip)  
Telephone: 1-866-532-3161

3. Find accommodation A big first step is finding accommodation. While you will have arranged temporary accommodation from your country of origin, now it’s time to find a good place to rent for the medium term. The best place to search for a rental is the internet and classified newspapers. You can also visit various neighborhoods, where you will likely see posters in front of some apartment buildings, advertising apartments for rent. Please see below links for rental houses and apartments: 
* (https://housinganywhere.com/s/Toronto--Canada) 
* (https://www.rentfaster.ca/) 
* (https://rentals.ca/) 
* (https://www.zumper.com/houses-for-rent/toronto-on) 

4. Set up a Bank Account Another priority in your first few days will be dealing with your finances. 

Select a bank or a credit union near your home or work and open at least one bank account right away. To open an account, you will need your landed immigrant papers and any other identification you have to prove your place of residence. 

Banks provide basic savings accounts and chequing accounts. You may need a chequing account in particular because many employers pay by direct deposit right into your account. Slowly, you can build a good relationship with your bank, and start building your credit history, by applying for a secured credit card and then a traditional credit card. To build a strong Canadian credit history, it’s important to pay your bills and loans in a timely manner. Your credit history will help you when you want to get a mortgage to buy a home, or get a loan to start a business.